#!/usr/bin/env python3
"""Render a release testing brief from tickets.json + rules.ini.

Reads a JSON file (release meta + a list of tickets, each ticket already
carrying an LLM-generated ``focus``) and the mechanical rules in rules.ini,
then emits a single Markdown brief with a table of contents and clickable
ticket anchors that jump from the must-test table to the detail entries.

Usage:
    python render_brief.py <tickets.json> [-o release-test-focus.md]

The script only does mechanical work (priority mapping, must-test selection,
sort, risk, anchor rendering). The semantic ``focus`` field per ticket is
generated by the LLM beforehand, following the rules in SKILL.md.

Pure standard library only (json, configparser, argparse, pathlib). No
third-party dependencies.
"""

import argparse
import configparser
import json
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
RULES_FILE = SKILL_DIR / "rules.ini"

RISK_LABEL = {
    "high": "🔴 High",
    "med_high": "🟠 Medium-high",
    "med": "🟡 Medium",
    "low": "🟢 Low",
}
RISK_REASON = {
    "high": "contains a P0 change",
    "med_high": "contains a breaking change or high-priority dependency upgrade",
    "med": "contains a P1 change",
    "low": "all changes are low priority",
}
SOURCE_LABEL = {"main": "Main", "dependency": "Dependency"}


def _split_list(raw: str) -> list:
    return [x.strip() for x in raw.split(",") if x.strip()]


def load_rules(path: Path) -> dict:
    """Parse rules.ini (stdlib configparser) into the nested dict the rest uses.

    Pure standard library — no third-party config dependency.
    """
    if not path.is_file():
        print(f"Error: rules file not found: {path}", file=sys.stderr)
        sys.exit(1)

    cp = configparser.ConfigParser(
        delimiters=("=",),
        comment_prefixes=("#", ";"),
        inline_comment_prefixes=("#", ";"),
    )
    cp.optionxform = str  # preserve case for type/source keys
    cp.read(path, encoding="utf-8-sig")

    def section(name: str):
        return cp[name] if cp.has_section(name) else {}

    # priority_mapping: "blocker = P0:100" -> {"blocker": {"tier": "P0", "weight": 100}}
    mapping = {}
    for key, val in section("priority_mapping").items():
        if ":" not in val:
            print(
                f"Error: rules.ini [priority_mapping] {key}='{val}' must be "
                f"'<tier>:<weight>'.",
                file=sys.stderr,
            )
            sys.exit(1)
        tier, weight = val.rsplit(":", 1)
        try:
            mapping[key.lower()] = {"tier": tier.strip(), "weight": int(weight.strip())}
        except ValueError:
            print(
                f"Error: rules.ini [priority_mapping] {key} weight must be an integer.",
                file=sys.stderr,
            )
            sys.exit(1)

    mt = section("must_test")
    try:
        must_test = {
            "priority_weight_min": int(mt.get("priority_weight_min", "70")),
            "sources": _split_list(mt.get("sources", "")),
            "description_keywords": _split_list(mt.get("description_keywords", "")),
        }
    except ValueError as e:
        print(f"Error: rules.ini [must_test] {e}", file=sys.stderr)
        sys.exit(1)

    def int_map(name: str) -> dict:
        out = {}
        for k, v in section(name).items():
            try:
                out[k] = int(v)
            except ValueError:
                print(f"Error: rules.ini [{name}] {k}='{v}' must be an integer.", file=sys.stderr)
                sys.exit(1)
        return out

    rs = section("risk")
    try:
        risk = {
            "high_weight": int(rs.get("high_weight", "100")),
            "med_high_dependency_weight": int(rs.get("med_high_dependency_weight", "70")),
            "med_weight": int(rs.get("med_weight", "70")),
            "low_weight_max": int(rs.get("low_weight_max", "30")),
        }
    except ValueError as e:
        print(f"Error: rules.ini [risk] {e}", file=sys.stderr)
        sys.exit(1)

    ns = section("nav")
    nav = {
        "enable_toc": ns.getboolean("enable_toc", fallback=True),
        "ticket_anchor_prefix": ns.get("ticket_anchor_prefix", "t-"),
        "back_to_top": ns.getboolean("back_to_top", fallback=True),
    }

    return {
        "priority_mapping": mapping,
        "must_test": must_test,
        "type_order": int_map("type_order"),
        "source_order": int_map("source_order"),
        "risk": risk,
        "nav": nav,
    }


def load_tickets(path: Path) -> dict:
    if not path.is_file():
        print(f"Error: tickets file not found: {path}", file=sys.stderr)
        sys.exit(1)
    with path.open(encoding="utf-8-sig") as f:
        return json.load(f)


def enrich(ticket: dict, rules: dict) -> dict:
    """Attach tier/weight/breaking/hits to a ticket using rules.ini."""
    prio = ticket.get("priority")
    mapping = rules["priority_mapping"]
    key = (prio or "").lower()
    if key not in mapping:
        print(
            f"Error: priority '{prio}' (ticket {ticket.get('id')}) is not in "
            f"rules.ini [priority_mapping]. Add it there before rendering.",
            file=sys.stderr,
        )
        sys.exit(1)
    entry = mapping[key]
    tier, weight = entry["tier"], int(entry["weight"])

    desc = (ticket.get("description") or "").lower()
    keywords = [str(k).lower() for k in rules["must_test"].get("description_keywords", [])]
    breaking = any(kw and kw in desc for kw in keywords)

    mt = rules["must_test"]
    hits = []
    if weight >= int(mt.get("priority_weight_min", 0)):
        hits.append("A")
    if ticket.get("source") in mt.get("sources", []):
        hits.append("B")
    if breaking:
        hits.append("C")

    return {
        **ticket,
        "tier": tier,
        "weight": weight,
        "breaking": breaking,
        "hits": hits,
        "must_hit_count": len(hits),
    }


def sort_key_factory(rules: dict, by_hits: bool):
    type_order = rules.get("type_order", {})
    source_order = rules.get("source_order", {})

    def key(t: dict):
        typ = type_order.get(t["type"], 99)
        src = source_order.get(t["source"], 99)
        if by_hits:
            return (-t["must_hit_count"], -t["weight"], typ, src)
        return (-t["weight"], typ, src)

    return key


def compute_risk(tickets: list, rules: dict) -> str:
    r = rules["risk"]
    weights = [t["weight"] for t in tickets]
    if not weights:
        return "low"
    if any(w >= int(r["high_weight"]) for w in weights):
        return "high"
    dep_floor = int(r.get("med_high_dependency_weight", 0))
    if any(t["breaking"] for t in tickets) or any(
        t["source"] == "dependency" and t["weight"] >= dep_floor for t in tickets
    ):
        return "med_high"
    if any(w >= int(r["med_weight"]) for w in weights):
        return "med"
    if all(w <= int(r["low_weight_max"]) for w in weights):
        return "low"
    return "med"


def anchor(prefix: str, ticket_id: str) -> str:
    return prefix + ticket_id.lower()


def count_by_type(group: list):
    stories = sum(1 for t in group if t["type"] == "Story")
    defects = sum(1 for t in group if t["type"] == "Defect")
    return stories, defects, len(group) - stories - defects


def _scope(n: int, stories: int, defects: int) -> str:
    items = f"{n} item{'s' if n != 1 else ''}"
    detail = []
    if stories:
        detail.append(f"{stories} Story")
    if defects:
        detail.append(f"{defects} Defect")
    return f"{items} ({', '.join(detail)})" if detail else items


def render(doc: dict, rules: dict) -> str:
    meta = doc.get("meta", {})
    tickets = [enrich(t, rules) for t in doc.get("tickets", [])]
    nav = rules.get("nav", {})
    prefix = nav.get("ticket_anchor_prefix", "t-")
    risk = compute_risk(tickets, rules)

    main_tickets = [t for t in tickets if t["source"] == "main"]
    dep_tickets = [t for t in tickets if t["source"] == "dependency"]
    must_tickets = [t for t in tickets if t["must_hit_count"] > 0]

    list_key = sort_key_factory(rules, by_hits=False)
    focus_key = sort_key_factory(rules, by_hits=True)
    must_tickets.sort(key=focus_key)
    main_tickets.sort(key=list_key)
    dep_tickets.sort(key=list_key)

    def back_to_top():
        if nav.get("back_to_top", True):
            return ["", "> [↑ Back to contents](#toc)", ""]
        return [""]

    version = meta.get("version", "unspecified")
    baseline = meta.get("baseline", "—")
    window = meta.get("window", "unspecified")

    lines = [f"# {version} Release Test Brief", ""]

    if nav.get("enable_toc", True):
        lines.append('<a id="toc"></a>')
        lines.append("## Contents")
        lines.append("- [§0 Overview](#sec-0)")
        lines.append("- [§1 Must-test priorities](#sec-1)")
        if main_tickets:
            lines.append("- [§2 Main-project changes](#sec-2)")
        if dep_tickets:
            lines.append("- [§3 Dependency upgrades](#sec-3)")
        lines += back_to_top()

    # §0 overview
    lines.append('<a id="sec-0"></a>')
    lines.append("## 0. Overview")
    lines.append(f"- Version: **{version}** (baseline {baseline}) | window: {window}")
    ms, md_, _ = count_by_type(main_tickets)
    ds, dd, _ = count_by_type(dep_tickets)
    lines.append(
        f"- Scope: main {_scope(len(main_tickets), ms, md_)} | "
        f"dependencies {_scope(len(dep_tickets), ds, dd)}"
    )
    lines.append(f"- Overall risk: **{RISK_LABEL[risk]}** — {RISK_REASON[risk]}")
    lines += back_to_top()

    # §1 must-test table
    lines.append('<a id="sec-1"></a>')
    lines.append("## 1. Must-test priorities")
    if not must_tickets:
        lines.append(
            "> No must-test items (no high-priority change, dependency upgrade, "
            "or breaking change)."
        )
    else:
        lines.append("| Ticket | Type | Source | Priority | Test focus |")
        lines.append("|---|---|---|---|---|")
        for t in must_tickets:
            raw_id = t["id"]
            aid = anchor(prefix, raw_id)
            tid = f"[{raw_id}](#{aid})"
            src = SOURCE_LABEL.get(t["source"], t["source"])
            focus = t.get("focus") or "—"
            lines.append(f"| {tid} | {t['type']} | {src} | {t['tier']} | {focus} |")
        lines.append("")
        lines.append(
            "> Must-test rule: weight ≥ {0} / dependency upgrade / breaking change "
            "(any one).".format(rules["must_test"].get("priority_weight_min", 70))
        )
    lines += back_to_top()

    # §2 main project changes
    if main_tickets:
        lines.append('<a id="sec-2"></a>')
        lines.append("## 2. Main-project changes")
        type_order = rules.get("type_order", {})
        present_types = sorted(
            {t["type"] for t in main_tickets},
            key=lambda ty: type_order.get(ty, 99),
        )
        for ty in present_types:
            heading = {"Story": "Stories", "Defect": "Defects"}.get(ty, ty)
            lines.append("")
            lines.append(f"### {heading}")
            for t in (x for x in main_tickets if x["type"] == ty):
                aid = anchor(prefix, t["id"])
                lines.append(f'<a id="{aid}"></a>')
                lines.append(f"- **{t['id']} ({t['tier']})** {t['title']}")
                focus = t.get("focus")
                if focus:
                    lines.append(f"  - Test focus: {focus}")
        lines += back_to_top()

    # §3 dependency upgrades
    if dep_tickets:
        lines.append('<a id="sec-3"></a>')
        lines.append("## 3. Dependency upgrades")
        lines.append("| Library | Version change | Ticket | Type | Priority | Regression hint |")
        lines.append("|---|---|---|---|---|---|")
        for t in dep_tickets:
            aid = anchor(prefix, t["id"])
            lib = t.get("library") or "—"
            ver = f"{t.get('version_from', '—')} → {t.get('version_to', '—')}"
            tid = f'<a id="{aid}"></a>[{t["id"]}](#{aid})'
            focus = t.get("focus") or "—"
            lines.append(
                f"| {lib} | {ver} | {tid} | {t['type']} | {t['tier']} | {focus} |"
            )
        lines += back_to_top()

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description="Render a release testing brief.")
    ap.add_argument("tickets", help="path to tickets.json")
    ap.add_argument(
        "-o",
        "--output",
        default="release-test-focus.md",
        help="output markdown path (default: release-test-focus.md)",
    )
    args = ap.parse_args()

    rules = load_rules(RULES_FILE)
    doc = load_tickets(Path(args.tickets))
    out = render(doc, rules)
    Path(args.output).write_text(out, encoding="utf-8")
    n = len(doc.get("tickets", []))
    print(f"Wrote {args.output} ({n} ticket{'s' if n != 1 else ''})")


if __name__ == "__main__":
    main()
